site_name: MathGrass (Backend & Infrastructure)
nav:
    - Home: index.md
    - User Guide:
      - 'Concepts & Domain': 'usage/concepts.md'
      - 'Usage': 'usage/usage.md'
    - Development & Operations:
      - 'Prerequisites': ./devops/prerequisites.md
      - 'Building & Deploying MathGrass': ./devops/build.md
      - 'OpenAPI Specification': ./devops/openapi.md
theme: readthedocs
