@startuml

title MathGrass Schemas Diagram

entity Edge {
    * firstVertex: Vertex
    * secondVertex: Vertex
    label: String
}

entity Feedback {
    id: Long
    content: String
}

entity Graph {
    * id: Long
    labels: List<Label>
    * edges: List<Edge>
    * vertices: List<Vertex>
}

entity Label {
    * id: Long
    * label: String
}

entity Question {
    * question: String
    isDynamicQuestion: Boolean
    taskSolver: TaskSolver
    * questionType: String
    answer: String
    possible_answers: List<String>
}

entity RunStaticAssessment200Response {
    * isAssessmentCorrect: Boolean
}

entity RunStaticAssessmentRequest {
    * answer: String
}

entity Task {
    * id: Long
    template: TaskTemplate
    * graph: Graph
    hints: List<TaskHint>
    feedback: List<Long>
    * question: Question
    label: String
    answer: String
}

entity TaskCollection {
    id: Long
    label: String
    tasks: List<Long>
}

entity TaskHint {
    * id: Long
    label: String
    * content: String
}

entity TaskIdLabelTuple {
    * id: Long
    * label: String
}

entity TaskResult {
    id: Long
    task: Long
    answer: String
    submissionDate: String
    evaluationDate: String
    answerTrue: Boolean
}

entity TaskSolver {
    id: Long
    label: String
    executionDescriptor: String
}

entity TaskTemplate {
    id: Long
    label: String
    question: String
    taskSolver: Long
    hints: List<TaskHint>
    labels: List<Label>
}

entity TaskTopic {
    id: Long
    label: String
    tasks: List<Long>
}

entity Vertex {
    * id: Long
    * x: Integer
    * y: Integer
    label: String
}


TaskTemplate -- "0..*" TaskHint : hints
TaskTemplate -- "0..*" Label : labels
Task -- TaskTemplate : template
Task -- Graph : graph
Task -- "0..*" TaskHint : hints
Task -- Question : question
Graph -- "0..*" Label : labels
Graph -- "0..*" Edge : edges
Graph -- "0..*" Vertex : vertices
Question -- TaskSolver : taskSolver
Edge -- Vertex : firstVertex
Edge -- Vertex : secondVertex

@enduml