@startuml

title MathGrass Schemas Diagram

entity EdgeDTO {
    * firstVertex: VertexDTO
    * secondVertex: VertexDTO
    label: String
}

entity Feedback {
    id: Long
    content: String
}

entity GraphDTO {
    * id: Long
    labels: List<LabelDTO>
    * edges: List<EdgeDTO>
    * vertices: List<VertexDTO>
}

entity LabelDTO {
    * id: Long
    * label: String
}

entity Question {
    * question: String
    isDynamicQuestion: Boolean
    taskSolver: TaskSolver
    * questionType: String
    answer: String
    possible_answers: List<String>
}

entity RunStaticAssessment200Response {
    * isAssessmentCorrect: Boolean
}

entity RunStaticAssessmentRequest {
    * answer: String
}

entity Task {
    * id: Long
    * graph: GraphDTO
    hints: List<TaskHint>
    feedback: List<Long>
    * question: Question
    label: String
    answer: String
}

entity TaskCollection {
    id: Long
    label: String
    tasks: List<Long>
}

entity TaskHint {
    * id: Long
    label: String
    * content: String
}

entity TaskIdLabelTuple {
    * id: Long
    * label: String
}

entity TaskResult {
    id: Long
    task: Long
    answer: String
    submissionDate: String
    evaluationDate: String
    answerTrue: Boolean
}

entity TaskSolver {
    id: Long
    label: String
    executionDescriptor: String
}

entity VertexDTO {
    * id: Long
    * x: Integer
    * y: Integer
    label: String
}


Task -- GraphDTO : graph
Task -- "0..*" TaskHint : hints
Task -- Question : question
GraphDTO -- "0..*" LabelDTO : labels
GraphDTO -- "0..*" EdgeDTO : edges
GraphDTO -- "0..*" VertexDTO : vertices
EdgeDTO -- VertexDTO : firstVertex
EdgeDTO -- VertexDTO : secondVertex
Question -- TaskSolver : taskSolver

@enduml